services:
  site:
    image: mvp-frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:5173
    volumes:
      - nodemodules:/app/node_modules
      - .:/app

volumes:
  nodemodules: {}